Homework for variable-declarations_by Norba Tamara
NorbaTamara/js-basic pull request #1
Opened 2019-10-07 16:09 UTC by NorbaTamara

2019-10-08 09:01 UTC, Mike-Savin requested changes

2019-10-08 09:01 UTC, Mike-Savin commented on Exercises/variables-declaration/variables-declaration.js
> +var sameName = 10;
Two variables with different names should contain different values at the same time. In your case second defined variable will overwrite the first one.

2019-10-08 09:01 UTC, Mike-Savin commented on Exercises/variables-declaration/variables-declaration.js
> +var sameName = 10;
Good work in general

2019-10-08 14:31 UTC, lizarusi requested changes
All good, just see @Mike-Savin comments

2019-10-09 18:52 UTC, NorbaTamara commented
Thank you :) 
Resolved.

2019-10-09 18:53 UTC, merged